spring.application.name=user-service

server.port=8082

#
# DB (adjust user/password as needed)
spring.datasource.url=jdbc:mysql://localhost:3306/pg_management_db
spring.datasource.username=root
spring.datasource.password=Yourpassword@123

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
#
## Eureka (register with eureka-server)
#eureka.client.service-url.defaultZone=http://localhost:8761/eureka
#
# Seed config
#app.initial.rooms=5   # number of rooms to create on startup (r1..rN)
app.initial.capacity=4

app.initialRooms=5
#
## Swagger/OpenAPI
#springdoc.api-docs.path=/v3/api-docs
#springdoc.swagger-ui.enabled=true
#springdoc.swagger-ui.path=/swagger-ui.html
#

eureka.client.enabled=false
spring.cloud.discovery.enabled=false
spring.cloud.loadbalancer.enabled=false




#
#spring.jpa.hibernate.ddl-auto=none
#spring.datasource.initialize=false

