spring.application.name=payment-service
# --- Server ---
server.port=8083

# --- Database ---
spring.datasource.url=jdbc:mysql://localhost:3306/pg_management_db
spring.datasource.username=root
spring.datasource.password=Yourpassword@123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=create


spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# --- Feign Client ---
# Enable Feign clients in your main class with @EnableFeignClients
# User Service base URL
user.service.url=http://localhost:8082/user

# --- Logging ---
logging.level.org.springframework.web=INFO
logging.level.com.pg.payment=DEBUG


# Swagger OpenAPI Configuration
# Swagger/OpenAPI
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html

server.error.include-message=always
server.error.include-binding-errors=always

spring.jpa.properties.hibernate.format_sql=true




eureka.client.enabled=false
spring.cloud.discovery.enabled=false
spring.cloud.loadbalancer.enabled=false




